stages:          # List of stages for jobs, and their order of execution
    - lint
lint-job:
    stage: lint
    script:
        - python3 -m venv pyvenv
        - source pyvenv/bin/activate
        - pip3 install -r requirements.txt
        - pylint ./parser
        - pylint ./analysis
        - cpplint --recursive --filter=-readability/casting parser/Nasdaq_Parser
# playground-job:
#     stage: playground
#     script:
#         - ls -lha
#         - export VAGRANT_CHECKPOINT_DISABLE=1
#         - export VAGRANT_HOME=$PWD/vagrant_home
#         - export | grep VAGRANT  
#         - vagrant up
#   - build
#   - test
#   - deploy

