variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
    paths:
        - .cache/pip
        - pyvenv/

before_script:
    - python -V               
    - python3 -m venv pyvenv
    - source pyvenv/bin/activate

stages:          # List of stages for jobs, and their order of execution
    - lint
    - build
lint-job:
    stage: lint
    script:
        - pip3 install -r requirements.txt
        - pylint ./parser/alpaca_parser
        - pylint ./analysis
        - cpplint --recursive --filter=-readability/casting parser/Nasdaq_Parser
build-job:
    stage: build
    script:
        - cd ./parser/Nasdaq_Parser
        - make
# playground-job:
#     stage: playground
#     script:
#         - ls -lha
#         - export VAGRANT_CHECKPOINT_DISABLE=1
#         - export VAGRANT_HOME=$PWD/vagrant_home
#         - export | grep VAGRANT  
#         - vagrant up
#   - build
#   - test
#   - deploy

